trainer:
  epochs: 10
  batch_size: 1

actor:
  optim:
    lr: 1e-5

critic:
  optim:
    lr: 1e-4

rollout:
  n_frames: 16
  ddim_steps: 10

model:
  oasis_ckpt: "oasis500m.safetensors"
  vae_ckpt: "vit-l-20.safetensors"

data:
  dataset_path: "../dataset/MiDaS-60_small/train"
